### ISSUE TITLE
The input processor of TeX will fold tabs and spaces into a single space token unless tab and space have their category changed from 10 (spacer) to 12 (other)

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#107]
``` tex
\catcode`\ =12
\catcode`\^^I=12
```

We may need to do this category-changing in `tests/templates/*/*.tex.m4` immediately before running the test, i.e. before `\beginMarkdown`/`\markdownInput`/`\startmarkdown`. Otherwise, at least the following tests will fail: 334, 335, 337.

 [1]: https://www.overleaf.com/learn/latex/Table_of_TeX_category_codes
 [2]: http://petr.olsak.net/ftp/olsak/tbn/tbn.pdf

_Originally posted by @Witiko in https://github.com/lostenderman/markdown/issues/1#issuecomment-1337186582_

**Comment by Witiko** [comment]
Can you please assign this issue to me?

**Comment by lostenderman** [comment]
Closing after pull #111.
