### ISSUE TITLE
Interior spaces in a code span should not be collapsed

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#17]
See <https://spec.commonmark.org/0.30/#example-337>

**Comment by Witiko** [comment]
This issue is a duplicate of issue #107.

**Comment by lostenderman** [comment]
Not closing after pull #111, example 337 fails.

Trailing spaces are not preserved in the output.

**Comment by Witiko** [comment]
@lostenderman TeX will always fold trailing spaces at the end of a line. We will likely need to delete the unit test similarly to https://github.com/lostenderman/markdown/issues/37.
