### ISSUE TITLE
A backslash before the line ending may be used instead of two or more spaces

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#38]
See <https://spec.commonmark.org/0.30/#example-634>

**Comment by Witiko** [comment]
This issue corresponds to [the `escaped_line_breaks` syntax extension of Pandoc][1], which is already tracked in https://github.com/Witiko/markdown/issues/210 and which has already been [implemented][2] in [the upstream lunamark library][3] and can be backported.

 [1]: https://pandoc.org/MANUAL.html#extension-escaped_line_breaks
 [2]: https://github.com/jgm/lunamark/pull/42
 [3]: https://github.com/jgm/lunamark
