### ISSUE TITLE
The destination cannot contain line endings, even if enclosed in pointy brackets

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#47]
See <https://spec.commonmark.org/0.30/#example-490>

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/009.test`:

``````````` md
%   ---RESULT--- "example": 489,
%   
%   <p>[link](foo
%   bar)</p>
%   
%   ---\RESULT---

<<<
[link](foo
bar)
>>>
documentBegin
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/009.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/009.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
    Template templates/plain/verbatim.tex.m4
      Command pdftex   --shell-escape                  --interaction=nonstopmode  test.tex
      Command xetex    --shell-escape --8bit           --interaction=nonstopmode  test.tex
      Command luatex                                   --interaction=nonstopmode  test.tex
```````````

I cannot reproduce any issues.

**Comment by lostenderman** [comment]
The wrong example was referenced.

Example https://spec.commonmark.org/0.30/#example-490; however, does fail due to the reason specified above.

The description has been updated accordingly.

**Comment by Witiko** [comment]
The corresponding unit test is `testfiles/CommonMark_0.30/links/010.test`:

``````````` md
%   ---RESULT--- "example": 490,
%   
%   <p>[link](<foo
%   bar>)</p>
%   
%   ---\RESULT---

<<<
[link](<foo
bar>)
>>>
documentBegin
inlineHtmlTag: <foo bar>
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/links/010.test"`:

```````````
Testfile testfiles/CommonMark_0.30/links/010.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2022-12-29 22:00:34.312689140 +0100
--- test-actual.log	2022-12-29 22:00:40.862622913 +0100
***************
*** 1,3 ****
  documentBegin
! inlineHtmlTag: <foo bar>
  documentEnd
--- 1,7 ----
  documentBegin
! BEGIN link
! - label: link
! - URI: foo bar
! - title: 
! END link
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing [autolinks][1], which use the rules for [Gruber's Markdown][2] rather than [CommonMark][3].

 [1]: https://github.com/Witiko/markdown/blob/e9aa96e399ef59929c2c161f85d324a5378d8db5/markdown.dtx#L21983-L22005
 [2]: https://daringfireball.net/projects/markdown/syntax#autolink
 [3]: https://spec.commonmark.org/0.30/#autolinks
