### ISSUE TITLE
Non-breaking space should map to nbsp by default

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#99]

**Comment by Witiko** [comment]
Can you please assign this issue to me?

**Comment by lostenderman** [comment]
Not closing issue with pull #117.

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/entity_and_numeric_character_references/001.test"`:

```
Testfile testfiles/CommonMark_0.30/entity_and_numeric_character_references/001.test
  Format templates/context/
    Template templates/context/input.tex.m4
      Command texexec  --passon="--shell-escape --8bit --interaction=nonstopmode" test.tex
*** test-expected.log   2023-01-13 18:27:45.157953900 +0100
--- test-actual.log     2023-01-13 18:27:47.897953900 +0100
***************
*** 1,5 ****
  documentBegin
! emphasis: (nbsp) (ampersand) © Æ Ď
  emphasis: ¾ ℋ ⅆ
! emphasis: ∲ ≧̸
  documentEnd
--- 1,5 ----
  documentBegin
! emphasis:   (ampersand) © Æ Ď
  emphasis: ¾ ℋ ⅆ
! emphasis: ∲ (ampersand)ngE;
  documentEnd
```

**Comment by Witiko** [comment]
@lostenderman My mistake. In witiko#247, I considered nbsp a character but in UTF-8, it's actually a two-byte string (`C2 A0`). Should be fixed in witiko#249. I will open a pull request here after witiko#249 has been automerged.

**Comment by Witiko** [comment]
@lostenderman #118 should close this issue.

**Comment by lostenderman** [comment]
Closing with pull #118.
